import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const rajdhaniSans = Rajdhani({
	variable: "--font-rajdhani-sans",
	subsets: ["latin"],
	weight: ["400", "700"],
});

const rajdhaniMono = Rajdhani({
	variable: "--font-rajdhani-mono",
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${rajdhaniSans.variable} ${rajdhaniMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
