import type { Metadata } from "next";
import "./globals.css";

// Note: Rajdhani font is defined in globals.css using @font-face or system fallbacks

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased overflow-x-hidden">
				{children}
			</body>
		</html>
	);
}
